# Generated by Django 3.0.5 on 2020-04-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apnapswrd', '0002_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
                ('message', models.TextField()),
            ],
        ),
    ]
