# Generated by Django 3.0.5 on 2020-04-30 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apnapswrd', '0004_contact_timestamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactus',
        ),
    ]
